title: DSC180AB B08
description: A starter template for a Jekyll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Sidebar Navigation (internal page anchors)
nav_order: 1
nav:
  - title: Home
    url: /
  - title: Background & Research Question
    url: /#background--research-question
  - title: Data Collections
    url: /#data-collections
  - title: Methodology
    url: /#methodology
  - title: Results
    url: /#results
  - title: Findings & Implications
    url: /#findings--implications
  - title: Future Directions
    url: /#future-directions
