title: DSC180AB B08
description: A starter template for a Jekyll site using the Just the Docs theme!

# Use remote_theme for GitHub Pages
remote_theme: just-the-docs/just-the-docs

# URL settings (update with your GitHub username and repository name)
url: "https://asdacdsfca.github.io"
baseurl: "/dsc180-b08-website"

# Auxiliary links (appears in the top right of the navbar)
aux_links:
  "Template Repository": https://github.com/just-the-docs/just-the-docs-template

# Enable necessary plugins
plugins:
  - jekyll-seo-tag

# Sidebar navigation order (remove nav section)
nav_order: 1
